### ISSUE TITLE
Feature flags don't seem to be propagated to tests created with composeStory

### ISSUE THREAD

**Issue by esquevin** [kodai3/storybook-addon-launchdarkly#1]
I'm using https://storybook.js.org/addons/@storybook/testing-react to create tests reusing my stories and feature flags sets with this addon does not seem to be properly propagated.

given a story
```
import { Story } from '@storybook/react';

import Component from '.';

export default {
  component: Component,
  parameters: {
    launchdarkly: {
      flags: {
        myFlagName: true,
      },
    },
  },
};

export const MyStory: Story<
  React.ComponentProps<typeof Component>
> = args => <Component {...args} />;
```

And a tests
```
import { composeStories } from '@storybook/testing-react';
import { render } from '@testing-library/react';

import * as stories from './stories';

const { MyStory } = composeStories(stories);

describe('Component', () => {
  it('should have flag as defined in story', () => {
    render(<MyStory />);
  });
});
```

The story will render with the flag set whereas the test, allegedly reusing the story configuration, wont.

It'd be a nice thing to have as I currently have to re set flags in my tests with jest-launchdarkly-mock.

PS: Thanks for your work on this addon, it's going to make my life easier!!

**Comment by kodai3** [comment]
@esquevin 
Thank you for the feedback !

I have not used flagged story for the test yet, so I didn't notice.
I'll look into this on this weekends.

**Comment by kodai3** [comment]
@esquevin 
you can check out the PR or updated Readme to test with out jest-launchdarkly-mock.
